### ISSUE TITLE
Install failure: broccoli-funnel and broccoli-merge-trees "Cannot find module"

### ISSUE THREAD

**Issue by JeffLuong** [Rastopyr/ember-cli-bricks#1]
I've tried installing this locally but am running into dependency issues. It seems like perhaps that `broccoli-funnel` and `broccoli-merge-trees` should be `dependencies` and not `devDependencies`?

Would like to hear any thoughts regarding this issue.

**Comment by Rastopyr** [comment]
Hi @JeffLuong, thank you for report.

Actually, now i did check install, and work of library and all is ok. Can you please answer to few questions for help fix this issue?

1) Which version of ember you using?
2) How you install this library?

**Comment by JeffLuong** [comment]
Thanks for getting back to me @Rastopyr 👍 

1. `ember: 2.10.0` & `ember-cli: 2.15.1`
2. I installed it using `npm install`

I just cloned this addon and moved `broccoli-funnel` and `broccoli-merge-trees` to `dependencies` in the `package.json` file and I was able to build my app properly.

I think these two dependencies are required for any app to build properly and can't just be `devDependencies`...some popular ember addons also have these two within `dependencies`:

ember-cli-sass:
https://github.com/aexmachina/ember-cli-sass/blob/master/package.json#L51

ember-cli-mirage:
https://github.com/samselikoff/ember-cli-mirage/blob/master/package.json#L35

ember-cli-babel
https://github.com/babel/ember-cli-babel/blob/master/package.json#L45

I can make a PR against this if you like!

**Comment by Rastopyr** [comment]
You are right! Pull Request is welcome!

**Comment by JeffLuong** [comment]
Done, thanks for the quick replies! https://github.com/Rastopyr/ember-cli-bricks/pull/2

**Comment by Rastopyr** [comment]
Thank to you! I'm did publish `1.0.10` version
@JeffLuong

**Comment by JeffLuong** [comment]
Thanks! 🚀
